<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Python学习笔记之try-except' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Python学习笔记之try-except</center></div><div class='banquan'>原文出处:本文由博客园博主雨夜Rainight提供。<br/>
原文连接:https://www.cnblogs.com/rainights/p/11765617.html</div><br>
    <p>Python使用被称为异常的特殊对象来管理程序执行期间发生的错误。每当发生让Python不知所措的错误时，它都会创建一个异常对象。如果你编写了处理该异常的代码，程序将继续运行；如果你未对异常进行处理，程序将停止，并显示一个traceback，其中包含有关异常的报告。</p>
<p>异常是使用try-except代码块处理的。try-except代码块让Python执行指定的操作，同时告诉Python发生异常时怎么办。使用了try-except代码块时，即便出现异常，程序也将继续运行：显示你编写的友好的错误消息，而不是抛出原始错误traceback信息。</p>
<p>下面举个例子：</p>
<p>在division.py中写入下面代码：</p>
<div class="cnblogs_code">
<pre><code><span style="color: #0000ff;">print</span>(5/0)</pre>
</div>
<p>意思就是把5除以0的结果打印出来，但是我们都知道0是不能作为除数的，所以这个肯定是会报错的。</p>
<p>&nbsp;执行结果如下：</p>
<div class="cnblogs_code">
<pre><code><span style="color: #008080;">1</span> <span style="color: #000000;">Traceback (most recent call last):
</span><span style="color: #008080;">2</span>   File <span style="color: #800000;">"</span><span style="color: #800000;">division.py</span><span style="color: #800000;">"</span>, line 1, <span style="color: #0000ff;">in</span> &lt;module&gt;
<span style="color: #008080;">3</span>     <span style="color: #0000ff;">print</span>(5/<span style="color: #000000;">0)
</span><span style="color: #008080;">4</span> ZeroDivisionError: division by zero</pre>
</div>
<p>返回了一个Traceback信息，在文件"division.py"的第1行有一个异常，异常对象为ZeroDivisionError，异常原因是：division by zero，并且停止运行程序。</p>
<p>这显然不是我们所希望的。</p>
<p>当你认为可能发生了错误时，可编写一个try-except代码块来处理可能引发的异常。你让Python尝试运行一些代码，并告诉它如果这些代码引发了指定的异常，该怎么办。</p>
<p>从上面的异常信息中，我们知道了是异常对象类型为ZeroDivisionError，要处理这类异常的try-except代码块可以这样写：</p>
<div class="cnblogs_code">
<pre><code><span style="color: #008080;">1</span> <span style="color: #0000ff;">try</span><span style="color: #000000;">:
</span><span style="color: #008080;">2</span>     <span style="color: #0000ff;">print</span>(5/<span style="color: #000000;">0)
</span><span style="color: #008080;">3</span> <span style="color: #0000ff;">except</span><span style="color: #000000;"> ZeroDivisionError:
</span><span style="color: #008080;">4</span>     <span style="color: #0000ff;">print</span>(<span style="color: #800000;">"</span><span style="color: #800000;">除数不能为0</span><span style="color: #800000;">"</span>)</pre>
</div>
<p>将引起异常的代码print(5/0)放在try中运行，如果try代码块中的代码运行起来没有问题，Python将跳过except代码块；如果try代码块中的代码导致了错误，Python将查找这样的except代码块，并运行其中的代码，即其中指定的错误与引发的错误相同。<br /><em id="__mceDel"><em id="__mceDel"><em id="__mceDel"></em></em></em></p>
<p>在这个示例中，try代码块中的代码引发了ZeroDivisionError异常，因此Python指出了该如何解决问题的except代码块，并运行其中的代码。这样，用户看到的是一条友好的错误消息，而不是traceback：</p>
<div class="cnblogs_code">
<pre><code><span style="color: #008080;">1</span> 除数不能为0</pre>
</div>
<p>&nbsp;</p>
</div>
</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>